apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rws7b0d4z-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rws7b0d4z-java-quarkus-gitops